### PR TITLE
fix travis cron job

### PR DESCRIPTION
**Pull request by fmessmer**
includes #38 
tries to fix the travis cron job

apparently `rosdep`'s issues with metapackages gives us some troubles here
@ipa-jba @ipa-fez @ipa-fmw FYI

### CODE REVIEW

**Comment by fmessmer** [comment]
Does anyone know what's happening here? @ipa-mdl?
`The job exceeded the maximum time limit for jobs, and has been terminated.` but continues to run for up to 6hr (https://travis-ci.org/ipa320/care-o-bot/jobs/278502998#L6343)

**Comment by mathias-luedtke** [comment]
Looks like a travis bug.
Or Docker resists the killing attempts pretty well ;)
Just cancel the job to unblock the slot.

**Comment by fmessmer** [comment]
I sent an e-mail to the travis-support...let's see what they say

**Comment by fmessmer** [comment]
reply from Travis-Support:

 > The issue you are experiencing is caused by a bug on our side - our workers currently fail to correctly update the build state if it hits a hard timeout.
We realize this is quite inconvenient and are working to fix it as soon as possible.
In the meantime, the only way around this issue is to prevent your builds from hitting the timeout. That being said, I've increased the timeout limit for your repo to 65 minutes instead of 50, hoping that it helps remediate things at least partly.

**Comment by fmessmer** [comment]
missing dependencies are requested at https://github.com/ros/rosdistro/pull/15990 and https://github.com/ros/rosdistro/pull/15991

**Comment by fmessmer** [comment]
ping @ipa-fmw @ipa-jba @ipa-fez @ipa-rmb

**Review by floweisshardt — APPROVED** [review]

**Pull request merged**
